const Items = [
  "Milk",
  "Curd",
  "Tomatoes",
  "Onions",
  "ChocoPillows x 2",
  "Honey Kellogs",
  "Fruits n Nuts Kellogs",
  "Aubergine",
  "Cabbage",
  "Cauliflower",
  "Lemons",
  "Cucumber",
  "Mushrooms",
  "Crumplets",
  "Bread",
  "Oats",
  "Yaprak",
  "Aubergine Dolma",
  "Frozen Veggies",
  "Peas",
  "Pasties",
  "Burgers",
  "Baby Corns",
  "Carrots",
  "Noodles",
  "Pasta",
  "Eggs",
  "Chillies",
  "Almond Milk",
  "Soya Milk",
  "Honey",
  "Bourbon",
  "McVitties Biscuit",
  "White Chocolate",
  "Milk Chocolate",
  "Dark Chocolate",
  "Hot Sauces",
  "Salsa",
  "Cashews",
  "Tomato Soup",
  "Minestrone Soup",
  "Vegetable Soup",
  "Tesco Chai",
  "Salt",
  "Chilli Powder",
  "Potatoes",
  "Ice Cream",
  "Chappati Flour",
  "Rice (10kg)",
  "Rice Flour",
  "Ragi Flour",
  "Toor Dal",
  "Urad Dal",
  "Electricity"
];

export default Items;
